### ISSUE TITLE
Global commands don't work on Linux/Mac: Add KRE_HOME to path on Linux

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnvm#149]
Today, we only do that for Windows. 

We need this for `kpm install global` because all commands are installed in the KRE's bin folder.

cc @anurse

**Comment by victorhurdugaci** [comment]
Can we please get this in for rc1?

`kpm commands install` doesn't work on *nix because of it.

**Comment by Praburaj** [comment]
`user-secrets` is affected by this change on mac/linux. @anurse do you plan to fix it for beta4?

**Comment by Praburaj** [comment]
@glennc

**Comment by davidfowl** [comment]
Why isn't there a falback.

**Comment by Praburaj** [comment]
It works by setting the path variable explicitly as a work around. It will be nice to fix it.

**Comment by anurse** [comment]
I can try to take a quick look in the beta4 timeline but my spare time is short with new runtime stuff :). @glennc has been doing some dnvm work, but not much in the linux space.

/cc @muratg @glennc for triaging and milestone application :).

**Comment by davidfowl** [comment]
What's the deal with this. Seems like this feature is busted without dnvm doing some magic here.

**Comment by victorhurdugaci** [comment]
Yup, dnvm needs to set that environment variable

**Comment by muratg** [comment]
@anurse let's get this done in beta 6.

**Comment by anurse** [comment]
I can make this change, and don't have a major problem with it, but it doesn't quite match with how other systems do this. `npm` for example drops global commands as shell files in `/usr/local/bin` which is already on the path. This does require sudo, but is generally the expected behavior.

Modifying the `PATH` is a more windows-centric model. Most *nix tools instead use `/usr/bin` and `/usr/local/bin` instead.

It might be best to briefly seek opinions from people more familiar with the POSIX world before finalizing this behavior. That can happen in parallel though, I'll be making this change shortly, since it is trivial and relatively safe.

**Comment by muratg** [comment]
@anurse sounds good, and I agree that following the conventions already used is a better idea. @davidfowl @lodejard any thoughts?

**Comment by anurse** [comment]
the downside of this is that the permissions for `/usr/local` are not unified across *nix variants. On my Mac it's owned by `anurse:admin` which Admin users can modify files there without sudoing. However, on my Ubuntu machine it's owned by `root:root` which means I need to `sudo npm install -g` (and would thus have to `sudo dnu commands install` as well)

**Comment by victorhurdugaci** [comment]
Adding it to a different folder would make uninstall complicated because it has to go through all the files in that folder

**Comment by anurse** [comment]
It definitely would. I'm curious how/if npm does this, I should take a look. I still think that if we can align with the platform-specific ways of doing things that would be better.
