### ISSUE TITLE
Fix AppVeyor badge in README

### ISSUE THREAD

**Issue by ghost** [aspnet/dnvm#245]
Docs: http://www.appveyor.com/docs/status-badges

Currently the badge is suggesting the build is failing while that is not the case: https://ci.appveyor.com/project/aspnetci/dnvm. 

It seems like the authorized person needs to get the renewed URL from https://ci.appveyor.com/project/aspnetci/dnvm/settings/badges.

**Comment by jasonwilliams200OK** [comment]
@muratg, OK so you decided close this issue because it is fixed, right? If it is fixed, there should be any reference or indication. If it is closed because you want the badge to keep lying: showing failure, when it is PASSING.. then please explain the rationale before quietly closing the issue. If you don't have time to explain, then please keep this issue open until you have some.
