### ISSUE TITLE
dnvm -list should show all available options to be installed

### ISSUE THREAD

**Issue by jchannon** [aspnet/dnvm#252]
other package managers have a -list command that show what versions can be installed ie/not just the ones on the local machine. That way you can see what you can upgrade/downgrade to from the remote feed

**Comment by glennc** [comment]
I don't know if I would define DNVM as a package manager. DNVM has two main functions. Download a zip and modify your path. Everything else is wrinkles for convenience.

Having said that, I'm ok with a feature like this. But thought needs to be put into what it is actually designed for. We can't just dump everything because the list would get really large really quickly. All combinations of arch, os, clr times all versions is not an insignificant number.

So what are the scenarios where you want to use this, and what information do you want to see?

**Comment by jchannon** [comment]
I guess listing those for your OS would be a good start

`dnvm install -list`

That would then show you what if can install.

We already have `dnvm install latest` so in simple terms it just needs to show those not installed on the machine?

**Comment by vsimonian** [comment]
:+1: This would be an invaluable feature - much more convenient than jumping between the browser and the console.

I second being able to see the ones for your OS - perhaps the last few versions?

An ability to put in a filter/search query would be a nice convenience, e.g. `dnvm list-remote` for the latest versions and `dnvm list-remote query` - I'm sure it wouldn't be a very complex addition and wouldn't be too tough to add.

**Comment by edudutra** [comment]
It would be great to have. And other version managers, like nvm for node, has this feature. In nvm (or nvmw for windows) it goes like this:

```
nvm ls-remote
```

**Comment by glennc** [comment]
Putting this one in the backlog. Seems like an ok feature to work on at some point.

**Comment by Tratcher** [comment]
:+1:
