### ISSUE TITLE
Get rid of "being overridden" noise

### ISSUE THREAD

**Issue by dougbu** [aspnet/dnvm#258]
`dnvm upgrade` and `dnvm install` now spits out useless yellow messages like

```
Default stable feed (https://www.nuget.org/api/v2) is being overridden by the value of the DNX_FEED environment variable (https://www.myget.org/F/aspnetvolatile/api/v2)
```

Since use set `DNX_FEED` themselves and it's visible in the environment, why remind them about it every time the variable is honoured?

**Comment by Eilon** [comment]
We could certainly make it less noisy. It should still probably give some hint about what's being used, though.

For default case: `Using default stable feed: {0}` (nuget.org)

For `-u` case: `Using default unstable feed: {0}` (myget.org)

For DNX_FEED case: `Using overridden DNX_FEED: {0}` (whatever custom feed)

**Comment by glennc** [comment]
We tell you every time it is honored because when upgrading from the version of dnvm that didn't have this to the version that does the variable was always set on non-windows machines. IIRC it was ok on Windows but on Linux or Mac you would have the variable set, and it would be set to aspnetvnext instead of NuGet.org. So we needed a way to tell people what was happening when they hit it.

I am certainly ok with the suggestion that @Eilon has though. I don't want to remove the information completely because it has helped people work out what is going on in the past.
