### ISSUE TITLE
dnvm install default" fails with nuget.org returning HTTP 400

### ISSUE THREAD

**Issue by MichaelKetting** [aspnet/dnvm#278]
I have set up a fresh system (Windows 10, VS2015RC, and a Windows 7, no VS) with:
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

When I run "dnvm install latest" the installation succeeds. When I run "dnvm install default", the installation fails with:

```
Downloading dnx-clr-win-x86.default from https://www.nuget.org/api/v2
Unable to download package: The remote server returned an error: (400) Bad Request.
At C:\Users\mk\.dnx\bin\dnvm.ps1:559 char:13
+             throw "Unable to download package: {0}" -f $Global:downlo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to downl...0) Bad Request.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to download package: The remote server returned an error: (400) Bad Request.
```

According to "dnvm", I'm using 
".NET Version Manager v1.0.0-beta6-10380"

It looks like this is related to some particular setup. I have a separate, older system (Windows 8.1, VS2015RC), which I updated to beta6 via "dnvm update-self", and there, "dnvm install default" works and gives me:

```
Downloading dnx-clr-win-x86.1.0.0-beta4 from https://www.nuget.org/api/v2
Installing to C:\Users\mk\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4
Adding C:\Users\mk\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4\bin to process PATH
Native image generation (ngen) is skipped. Include -Ngen switch to turn on native image generation to improve application startup time.
```

Any ideas what I'm doing wrong? 

Best regards, Michael

**Comment by glennc** [comment]
This is probably a bug, in that we should handle this case. But I think the cause is that you don't have a default alias on the machine that it's broken on. If you've only run dnvm install and not upgrade then you will not have a default dnx defined.

`dnvm install default` just re-downloads whatever dnx is in your default alias. It is designed to allow you to use the default dnx to specify some of your args. For example, `dnvm install defailt -arch x64` would install the 64 bit version of whatever dnx the default alias points to, even if that one is 32 bit.

Am I correct that you don't have a default alias on the broken machine?

**Comment by MichaelKetting** [comment]
@glennc Yeah, that's it. Also noticed that after some additional playing around on the machine, I now do have the default.txt set and it works. When I remove the file, same error as before. Am I correct in assuming this would then be the bug, i.e. the installer not setting up a default for dnvm?
