### ISSUE TITLE
dnvm install partially fails on Win7

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnvm#301]
dnvm install will install a runtime on Win7 but will then fail with:

![image](https://cloud.githubusercontent.com/assets/1438884/8221515/7dfbc42a-1514-11e5-9e9a-dc4fa69cda2a.png)

(Looks like assemblies won't get NGen'd)

**Comment by moozzyk** [comment]
@muratg - I think this basically means you cannot have native images on Win7. Not sure if it is beta5 or not.

**Comment by muratg** [comment]
@glennc

**Comment by MTRo** [comment]
I also had same issue.
It disappeared after I installed PowerShell with  "Windows Management Framework 4".

https://www.microsoft.com/ja-jp/download/details.aspx?id=40855

I guess. actual issue is this? 

https://social.technet.microsoft.com/Forums/windowsserver/en-US/48808b44-eb92-4470-8ad8-ed6d59b18e0c/how-to-read-a-64-bit-registry-from-a-32-bit-desktop

**Comment by moozzyk** [comment]
@MTRo you can "workaround" this by using the `-NoNative` option (or probably by installing PowerShel 3)
