### ISSUE TITLE
-NoNative vs. -NGen - inconsistent naming

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnvm#304]
Naming of the parameters seems inconsistent. 'NoNative' does not seem to be an opposite to 'NGen'

**Comment by davidfowl** [comment]
History https://github.com/aspnet/dnvm/pull/158

**Comment by glennc** [comment]
Change to -Optimize and -NoOptimize
-NoNative and -NGen need to keep working, but don't need to appear in help. We can't break peoples CI servers.

Need to investigate the ability to optimize a DNX that is already installed. Could be that running install on an existing install with -optimize just optimizes instead of throwing. Could be a top level command.
