### ISSUE TITLE
Rewriting dnvm in Python

### ISSUE THREAD

**Issue by arthrp** [aspnet/dnvm#379]
It seems like the dnvm keeps growing in size and soon will be > 1000 lines of code in a single script file. IMO it would make sense to rewrite the app in some cross-platform general purpose language like Python.

Motivation:
- Maintaining large codebases in Bash/Powershell is tedious. It's much less pain in Python.
- Python would allow to have _one_ codebase for all platforms (as opposed to bash/powershell scripts at moment). This would eliminate all the possible differences between scripts, which is a big gain.
- Python is by default on many OSes (e.g. many popular Linuxes, OS X). 

What do you think?

**Comment by anurse** [comment]
We've talked about doing something like this but it has a number of issues:

1. We will always need to use shell scripts as stubs at least because that's the only way to modify the `PATH` for a specific shell
2. Most scripting languages are not provided by default on enough OSes for us to use. Windows has only PowerShell and VBScript available by default, and while Python is often available by default, it is not guaranteed.
3. The time investment in porting isn't valuable enough for us to do it in the 1.0.0 RTM timeframe
4. If we were to write a single cross-platform DNVM it would make the most sense to use C# and CoreCLR, but things aren't quite ready for that to work in production yet, and won't be until after RTM. Investing in a rewrite now just to rewrite it again in C# would not be verify efficient.

So in general, we completely agree with and understand the issue, but I don't think this is going to happen for RTM. It's certainly something we'd be up for working with the community on as things settle down for the 1.0 release. Right now I think there's just a little too much "if it ain't broke don't fix it" mentality for us to go down this path today :).

Ping @muratg @Eilon - I think we could put this on the post-1.0 Backlog for consideration since I do think rewriting it in a cross-platform language is valuable, but I don't think we can fit this in the, already crowded, 1.0 timeline :)

**Comment by Eilon** [comment]
Agree with @anurse . I don't think Python is an option in the near term.

**Comment by muratg** [comment]
Thank you for the recommendation and ideas, @arthur-peka. 

I also agree 100% with @anurse. We can potentially consider some additional capability of including a runtime (AKA DNX) within the command package and rewrite DNVM in C#, but like @anurse says, this is something we would consider post V1 given the time investment. Putting this in backlog for now to consider once we have V1 out.
