### ISSUE TITLE
why the Install Path  is some user's path ?

### ISSUE THREAD

**Issue by jeff881208** [aspnet/dnvm#388]
why the default  installed path  is some user's path ?  I think  it should be a global path for everyone .

**Comment by jeff881208** [comment]
Both the dnvm and dnx.

**Comment by Eilon** [comment]
Can you show exactly what you're seeing? Which install path are you referring to?

**Comment by glennc** [comment]
You mean why does dnx and dnvm go into your user profile?

We are about to start working on a global installer for DNVM as well as a way to install the DNX in a global location when doing `dnvm install`. I assume both of those would solve your issues with it?

**Comment by jeff881208** [comment]
Yes ！You are right ! Thanks

**Comment by jeff881208** [comment]
It also should be that when upgrading..

**Comment by glennc** [comment]
--global has been added as an option when installing and upgrading now. It isn't the default, but if you prefer it then you can do that instead of putting them in your user profile. There isn't a super nice way to get DNVM globally installed at the moment, that will come, but you could put it somewhere outside of your user profile and add it to your path manually if you want nothing in your user profile.
