### ISSUE TITLE
Dnvm upgrade -u should use the new aspnetlitedev feed

### ISSUE THREAD

**Issue by Boglen** [aspnet/dnvm#401]
.. to get beta8 dnx

**Comment by glennc** [comment]
No, aspnetlitedev is too unstable for -u :). That feed has packages that are built but haven't had tests or anything completed on them yet. It is primarily designed for people working on the product itself to unblock themselves if they need the latest packages for something.

You aren't seeing beta8 on aspnetvnext because of build issues that we should have sorted out shortly.
