### ISSUE TITLE
Dnvm upgrade CLR -> 32bit; CoreCLR-> 64bit

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/dnvm#403]
Not sure why but it looks like when you upgrade with `-r clr` the default bitness is 32 bit while with `-r coreclr` it is 64 bit...

```
PS C:\Users\victo> dnvm upgrade -r clr
Determining latest version
'dnx-clr-win-x86.1.0.0-beta6' is already installed.
Adding C:\Users\victo\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin to process PATH
Adding C:\Users\victo\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-beta6'

PS C:\Users\victo> dnvm upgrade -r coreclr
Determining latest version
'dnx-coreclr-win-x64.1.0.0-beta6' is already installed.
Adding C:\Users\victo\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta6\bin to process PATH
Adding C:\Users\victo\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-beta6\bin to user PATH
Updating alias 'default' to 'dnx-coreclr-win-x64.1.0.0-beta6'
```

**Comment by BrennanConroy** [comment]
@glennc 

I don't see a huge problem with this, but maybe consistency across the clrs is what users would want.

**Comment by victorhurdugaci** [comment]
I haven't tried it on a 32 bit machine it might install the 64 bit version

**Comment by glennc** [comment]
64 bit is the default for consistency of CoreCLR across OS. Because there is no 32bit on Linux or Mac. So CoreCLR defaults to x64 everywhere and CLR defaults to 32 everywhere.

Did you find this particularly confusing or strange? or was it just something you noticed and wanted to log? Originally it defaulted to 32 on windows and 64 on other platforms and we could go back to that if there is a compelling reason to do so.

**Comment by xplicit** [comment]
When I run `dnvm upgrade -r coreclr` on 32 bit OS, it installs 64 bit version. If there is no 32 bit version ready yet it should say something like "CoreCLR could not be installed on 32-bit systems"
