### ISSUE TITLE
kvm install fails adding kre folder to path when kre_home is pointing to a directory other than %userprofile%/.kre

### ISSUE THREAD

**Issue by kirthik** [aspnet/dnvm#77]
Kre_Home variable is pointing to C:\Program Files\KRE

When I run `kvm install latest -amd64 -r CLR`, I see the following error

```Determining latest version Downloading KRE-CLR-amd64.1.0.0-beta1-10523 from https://www.myget.org/F/aspnetvnext/api/v2 Unpacking to C:\Users\kirthik\.kre\packages\temp Installing to C:\Users\kirthik\.kre\packages\KRE-CLR-amd64.1.0.0-beta1-10523 Cannot find KRE-CLR-amd64.1.0.0-beta1-10523, do you need to run 'kvm install 1.0.0-beta1-10523'?```

Based on the error, its not clear what is going on. Specially because kre does get installed in %userprofile%/.kre. 
I had to debug through the powershell script to see what was happening. It looks like this is happening in Locate-KreBinFromFullName() in kvm.ps1. If kre_home variable is set, then we look for package in kre_home path (In my case, since kre_home is not pointing to %userprofile%/.kre), script is not able to find the package to add to path.

We should either not throw an error when kre_home is not set to %userprofile%/.kre or install the runtime to a place where kre_home is set.

**Comment by muratg** [comment]
This is in userprofile now

**Comment by muratg** [comment]
@CumpsD there's a separate discussion tracked elsewhere about where we place various bits. But I'm curious why you may want to avoid these two places.  Is it because you want to use another drive which may have more space?

**Comment by CumpsD** [comment]
I have most of my development tools setup in a portable way, synced either via Google Drive or another sync tool. This usually always works fine, with the note that it has to be in my PATH. If I remember correctly, KRE decided hardcoded where to end up, as well as fiddling with the PATH, which hindered my setup.

To give you an idea my synced folder now has Android SDK, Atom, Beyond Compare, Cmder, F#, Go, Heroku tools, Hub, MySQL Workbench, Node + Global Node_modules, Nuget, PHP, Python, Ruby and Jekyll. All of these work flawlesly.

To be honest, I haven't touched KRE anymore since december since it didn't even install properly as a non administrator.
